### ISSUE TITLE
Unnecessary/potentially dangerous, but probably-not-really "free"

### ISSUE THREAD

**Issue by lucastcox** [VedantParanjape/esp-wifi-logger#5]
Just a warning about the following line: 

https://github.com/VedantParanjape/esp-wifi-logger/blob/5894f93becf56bcd2659509975207581a6602e63/wifi_logger.c#L88

If the xQueueReceive returns pdFalse, that means nothing was returned, so freeing the pointer would result in a coredump. 

Granted, this is only an issue if xqueuReceive returns pdFALSE with portMAX_DELAY, so I'm not quite sure how that could even happen, hence the title of this "issue." :)

**Comment by VedantParanjape** [comment]
Hey, thanks for reporting this, It would crash at configASSERT() before that, so I overlooked it.
Fixed in the issue in c8a9cbf. If you find this project useful, star the project.

Regards,
Vedant Paranjape

**Comment by lucastcox** [comment]
Haha. Totally missed that configAssert.

**Comment by VedantParanjape** [comment]
Hey, I have done the same thing in https://github.com/VedantParanjape/esp-wifi-logger/blob/c8a9cbfc7c93817aafdf9d2a9bbb3a47f2e7f29c/wifi_logger.c#L93.
Should this be removed too ?

Regards, 
Vedant Paranjape

**Comment by DhruvaG2000** [comment]
Just to be sure, this "potentially dangerous" issue still persists or has been fixed/ or was it never an issue?

**Comment by VedantParanjape** [comment]
> Just to be sure, this "potentially dangerous" issue still persists or has been fixed/ or was it never an issue?

It's fixed as of now.
