### ISSUE TITLE
Websocket code is not working as expected

### ISSUE THREAD

**Issue by shivam5594** [VedantParanjape/esp-wifi-logger#7]
I tried all 3 UDP, TCP and Websocket. 
For UDP and TCP I was able to get my print on my listening port on laptop.

But for Websocket, I see this 
```
E (2838) websocket_handler: Client not connected
I (2838) websocket_handler: WEBSOCKET_EVENT_CONNECTED
I (13138) websocket_handler: WEBSOCKET_EVENT_DATA
I (13148) websocket_handler: Received opcode=10
W (13148) websocket_handler: Received=  
I (23378) websocket_handler: WEBSOCKET_EVENT_DATA
I (23378) websocket_handler: Received opcode=10
W (23378) websocket_handler: Received=  
I (33628) websocket_handler: WEBSOCKET_EVENT_DATA
I (33628) websocket_handler: Received opcode=10
W (33628) websocket_handler: Received=  
I (43878) websocket_handler: WEBSOCKET_EVENT_DATA
I (43878) websocket_handler: Received opcode=10
W (43878) websocket_handler: Received=  
I (54108) websocket_handler: WEBSOCKET_EVENT_DATA
I (54108) websocket_handler: Received opcode=10
W (54118) websocket_handler: Received=  
```
It doesn't reach to my ESP_LOGI() function. 

My main looks like 
```
void app_main(void)
{
    start_wifi_logger();
    ESP_LOGI("MY_TAG","Looks like we connected.\n");
}
```

I am listening on laptop using websocket -s \<IP\>:\<PORT\>

**Comment by VedantParanjape** [comment]
Hi, can you post output of the following files/commands here:

1) sdkconfig
2) `ifconfig`

Did you use websocat to receive the logs? One needs to start a websocket server and then esp32 as a client connects to it.

You need to first install `websocat` from here: https://github.com/vi/websocat

and then use this command to start a websocket server.

websocat -s <IP_ADDRESS_OF_YOUR_MACHINE>:<PORT>

**Comment by shivam5594** [comment]
Yes, I have installed websocat from there and I am using the same command as you have mentioned in your readme.md
sdkconfig:
![image](https://user-images.githubusercontent.com/26493198/98077164-8beaaa00-1e24-11eb-9aea-916bdfd9a0bb.png)

This is what I see in server on laptop 
![image](https://user-images.githubusercontent.com/26493198/98077255-b89ec180-1e24-11eb-9018-c0e10a9ce820.png)

and same messages are seen on ESP side. 

I have tried the websocket example in ESP-IDF, and I can send the data over and it works fine with it. I am sure server side is working fine.

**Comment by shivam5594** [comment]
Looks like it is a Ping-Pong frames between server and client. according to [this](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers)

**Comment by shivam5594** [comment]
it worked after I kept the log function in the loop.
```
void app_main(void)
{
	start_wifi_logger();
	while(1)
		ESP_LOGI("MY_TAG","Looks like we connected.\n");
}
```

**Comment by VedantParanjape** [comment]
> it worked after I kept the log function in the loop.
> ```
> void app_main(void)
> {
> 	start_wifi_logger();
> 	while(1)
> 		ESP_LOGI("MY_TAG","Looks like we connected.\n");
> }
> ```

This is wierd, can you share your complete app folder, so that I can reproduce this issue and try to fix this.

But what gui are you using for sdkconfig? I mean the file sdkconfig in root directory.

**Comment by shivam5594** [comment]
I am using Eclipse for ESP_IDF. 

I think it is this piece of code
```
void websocket_event_handler(void *handler_args, esp_event_base_t base, int32_t event_id, void *event_data)
{
    esp_websocket_event_data_t *data = (esp_websocket_event_data_t *)event_data;
    switch (event_id) {
        case WEBSOCKET_EVENT_CONNECTED:
            ESP_LOGI(TAG, "WEBSOCKET_EVENT_CONNECTED");
            break;

        case WEBSOCKET_EVENT_DISCONNECTED:
            ESP_LOGI(TAG, "WEBSOCKET_EVENT_DISCONNECTED");
            break;

        case WEBSOCKET_EVENT_DATA:
            ESP_LOGI(TAG, "WEBSOCKET_EVENT_DATA");
            ESP_LOGI(TAG, "Received opcode=%d", data->op_code);
            ESP_LOGW(TAG, "Received=%.*s\r\n", data->data_len, (char*)data->data_ptr);
            break;

        case WEBSOCKET_EVENT_ERROR:
            ESP_LOGI(TAG, "WEBSOCKET_EVENT_ERROR");
            break;
    }
}
```
This is not a bug or something strange. I believe it happens since there is no more messages coming from ESP, and the one message sent is in buffer, server is sending ping-pong. I think just need to handle it here, as if it is ping-pong message then don't print if asked explicitly. 

Here is the code 
[ESP32_WiFi2.zip](https://github.com/VedantParanjape/esp-wifi-logger/files/5490321/ESP32_WiFi2.zip)

**Comment by VedantParanjape** [comment]
@shivam5594 Figured the error, actually that message is added to the message queue, as well as those event-handler messages(ping-pong frames), but websocket connection manager works differently than that of tcp/udp. Even though the client is not connected to the server, it will send that initial log message (user sent) and then fail to do so, and keep on doing this till it actually connects. Since the original log message has been removed from the message queue long back, you don't receive it.

This was a very well hidden bug in my original design.

So, here's the issue, I receive the message from the queue, then try to send it. If it fails, I just print a log message, rather than putting it back into the queue or retrying until it is sent actually.

I can fix this in the following two ways:
1) Try to send it until it actually does.
2) Don't actually receive message from queue, unless network interface is up and running.

Okay, so dug more into this, and realized that why this didn't happen in TCP/UDP case. Since `connect()` is a blocking call, while it's counterpart in websocket handler isn't, it keeps on trying to connect even after failing initially which the tcp/udp doesn't.

**Comment by shivam5594** [comment]
I thought the same. I was about to suggest that if we wait until the first successful ping-pong transaction, that could be a better way to tell if we are successfully connected. 

My take on your option 1:
Lets say there are 4 messages in queue and you take it and send it and you push it back in if it fails. 

If it failed for first 2 and succeeded in 3rd, the log print order will change. It will send 3rd, 4th, 1st and 2nd. Which can be misleading.

**Comment by VedantParanjape** [comment]
> I thought the same. I was about to suggest that if we wait until the first successful ping-pong transaction, that could be a better way to tell if we are successfully connected.
> 
> My take on your option 1:
> Lets say there are 4 messages in queue and you take it and send it and you push it back in if it fails.
> 
> If it failed for first 2 and succeeded in 3rd, the log print order will change. It will send 3rd, 4th, 1st and 2nd. Which can be misleading.

Agreed, pushing back can be misleading, I'll check if somehow I can rather peek and pop from the queue only if I successfully send the message. 

I went forward with making the send function blocking, atleast for now as follows. If you can submit a PR with the above change it will be great. I added the following to make it wait forever.

`while(!esp_websocket_client_is_connected(network_handle));`

I did this change only for websocket case, do you think, I should do the same for TCP/UDP ? make the connect function block until it connects successfully ?

Anyways, git pull and check if it runs correctly on your earlier example, this one to be exact, I have committed a possible fix, which worked on my system: 

```c
void app_main(void)
{
    start_wifi_logger();
    ESP_LOGI("MY_TAG","Looks like we connected.\n");
}
```

**Comment by shivam5594** [comment]
Changes you made is working. It sent the message. But I still see the ping-pong messages 

![image](https://user-images.githubusercontent.com/26493198/98173883-b9793700-1ea8-11eb-8806-ee1f93e56167.png)

I'll try to work on it while working on the issue I mentioned [above](https://github.com/VedantParanjape/esp-wifi-logger/issues/7#issuecomment-721968819) and send the pull req. 

Thanks for the quick fix.

**Comment by VedantParanjape** [comment]
Hi, the ping-pong messages will be seen as you have enabled the route systems logs options, so websocket handler spits out some logs, which also get added to the message queue, I'll change their log level to Debug, then they won't be seen by the user and aswell won't get added in the message queue.

**Comment by shivam5594** [comment]
okay, closing this issue since the main prob is solved. Thanks @VedantParanjape

**Comment by VedantParanjape** [comment]
@shivam5594 I gave this problem some thought. I came up with 3 solutions:

1) make the function `tcp_network_manager()` blocking, i.e. make it retry to connect until it does like this

```c
int err = -1;
while(err != 0)
{
   err = connect(nm->sock, (struct sockaddr *)&nm->dest_addr, sizeof(nm->dest_addr));
}
    if (err != 0) {
        ESP_LOGE(TAG, "Socket unable to connect: errno %d", errno);
        tcp_close_network_manager(nm);
        nm->sock = -1;
    }
    else
    {
        ESP_LOGI(TAG, "%s", "Successfully connected");
    }
```

2) Use `xQueuePeek()` to receive the front element in the message queue, and if it sent successfully, only then pop it from queue using `xQueueReceive()`, changes will be needed in send function

3) Make the send function blocking by adding something like this at the top, so that the function won't go into popping and receiving part:
`while(is_network_connected());`
But, then in this case we need to implement a event handler which will try to connect to the server again and again, just like the websocket handler does.

In my opinion, the 3rd option is going to be the most appropriate and neat !

**Comment by shivam5594** [comment]
@VedantParanjape Those are some good ideas. I feel while(); is a blocking statement. Instead of that, what about using semaphore when the state machine (event handler) says it is connected, release a semaphore and that is until the state goes back to disconnected or to error when take back the semaphore and try recovering the system. 

I liked the 2nd option. You can also add in front instead of add in front by QueueSendToFront() if you are continue using QueueReceive()

**Comment by VedantParanjape** [comment]
> @VedantParanjape Those are some good ideas. I feel while(); is a blocking statement. Instead of that, what about using semaphore when the state machine (event handler) says it is connected, release a semaphore and that is until the state goes back to disconnected or to error when take back the semaphore and try recovering the system. 
> 

Okay, But I am unable to understand how will a semaphore solve this issue, can you elaborate more on this.

> I liked the 2nd option. You can also add in front instead of add in front by QueueSendToFront() if you are continue using QueueReceive()

I don't think I can do that, freeRTOS port of esp32 hasn't documented that function, even though it is there in the header file.

But what are the tradeoff of using QueuePeek vs QueueSendToFront

**Comment by shivam5594** [comment]
> Okay, But I am unable to understand how will a semaphore solve this issue, can you elaborate more on this.

If we wait until the ESP driver changes the state to connected, and once it is changed to that, we know it is connected so releasing the semaphore will make sure that even the efforts are reading from queue and sending will be done after the successful connection. 

Additionally while(); won't give up the CPU since it is a blocking function. If we wait for a semaphore in while() inside main(), it will make sure that other tasks get the CPU. For us we get all the traces made even before connection was established. 

>I don't think I can do that, freeRTOS port of esp32 hasn't documented that function, even though it is there in the header file.
>But what are the tradeoff of using QueuePeek vs QueueSendToFront

I see that function in ESP32 FreeRTOS [doc](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos.html#c.xQueueSendToFront). 
I was just suggesting in case you don't want to change other functions like xQueueReceive().

QueuePeek: is a better idea I feel. Might have to change few more lines.
QueueSendToFront: Quick fix and might not have to change the current code flow.
